# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
latex: false
r_build_args: '--no-build-vignettes'
dist: trusty

matrix:
  include:
    - r: 3.4
    - r: 3.5
    - r: release
    - r: devel

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'