language: r

services:
  - docker

env:
  global:
    - CACHE_IMG=kfoltynski/cachemer:3.6.1
    - TEST_IMG=cachemer:3.6.1
    - DOCKERFILE=Dockerfile-R3.6.1

before_install:
- docker pull ${CACHE_IMG}
- docker build --cache-from ${CACHE_IMG} -t ${TEST_IMG} -f ${DOCKERFILE} .
- ls -la
- docker run -it -e PASSWORD=test -v $(pwd):/mnt/vol -w /mnt/vol ${TEST_IMG} R CMD check src --no-manual

script:
- true
