language: r

services:
  - docker

env:
  global:
    - CACHE_IMG=kfoltynski/cachemer:3.6.1
    - TEST_IMG=cachemer:3.6.1
    - DOCKERFILE=Dockerfile-R3.6.1

before_install:
- docker pull ${CACHE_IMG}
- docker build --cache-from ${CACHE_IMG} -t ${TEST_IMG} -f ${DOCKERFILE} .
- ls -la
- docker run -d -e PASSWORD=test -v $(PWD):/mnt/vol -w /mnt/vol ${TEST_IMG} /bin/sh -c "R CMD check src"

script:
- R CMD check src
