# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
latex: false
fortran: false
r_build_args: '--no-build-vignettes'
dist: trusty

matrix:
  include:
    - dist: trusty
      r_check_args: '--ignore-vignettes'
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:ubuntugis/ppa'
          packages:
            - libmagick++-dev
            - librsvg2-dev
            - libwebp-dev
            - libpoppler-cpp-dev
            - libtesseract-dev
            - libleptonica-dev
            - tesseract-ocr-eng
            - r-cran-rgdal
            - libfftw3-dev
    - r: 3.4
    - r: 3.5
    - r: release
    - r: devel

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'