# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
latex: false
r_build_args: '--no-build-vignettes'
dist: trusty

jobs:
  include:
    - r: 3.4
    - r: 3.5
    - r: release
    - r: devel

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false

r_packages:
  - covr

after_success:
  - Rscript -e 'Sys.setenv(TRAVIS = TRUE); covr::codecov()'
  - Rscript -e 'Sys.setenv(TRAVIS = TRUE); covr::coveralls()'
  
notifications:
  email:
    on_success: never
    on_failure: always
